### PR TITLE
Make homepage even more awesomer!

### PR DESCRIPTION
**Pull request by sarah-arrrgh**
Keen to get what I've done so far into master and carry over the rest of the undone todos to a new branch. I'm away for two weeks so then either I can pick it up again when I'm back or someone else can pick it up easily <3

## TODO:

- [x] update ButtonOutline component to receive colour info as props (buttons are different colours but the border and text are always the same colour)
- [x] Update homepage copy (https://docs.google.com/document/d/160PbbLUn2WdkVlVRTvUnnQMluM-OkbWzoR4CoapV6k8/edit?ts=5a3ae427)
- [x] Break down homepage into smaller components (tooooo yuuuuuge)
- [x] Add the values icons in the current placeholder container in section 3
- [x] How to use `textTransform` on button label text (currently `uppercase`, will not `capitalize` within ButtonOutline inline `style`, or `labelStyle` inside inline `style`)
- [x] Remove `text-decoration` on some button text (tried `textDecoration: 'none'` on buttons inline style and inline `labelStyle`, but to no avail :(
- [x] Sort out fonts - seems the "logo" font is really just the default font
- [x] Get all the partner logos into the Google Drive (can we have them as svgs, @SlimeyD ?)
- [x] Fix partner logo image scaling - when the screen width is small it distorts the images :(
- [x] Change colour of sign up button on three across section
- [x]  Line up the Yes and No section in section 3
- [ ] Fix styling in partner text to include links, italics, bold etc. (is there an easy way to do this @ahdinosaur ? The only way I can think of doing it is to break down each sentence into sub-sentences and add different styling to each part, which sounds like a pain in the ass...)
- [ ] Add section 5 copy when it's ready
- [ ] Add "DIsclaimer & Legals" in at the bottom of the page
- [ ] Get nav bar to stick to top of page (maybe diff branch)
- [ ] Why does the server only sometimes hot reload?
- [ ] Change color of SVGs in section 2 (unsure if this is necessary and not sure how to do it...)
- [ ] Make everything responsive - currently designed for desktop (read brand guidelines to make sure we're meeting each brands requirements in terms of spacing, placement, size etc.)

### CODE REVIEW

**Comment by SlimeyD** [comment]
@sarah-arrrgh I've requested these brand assets and .svg files from all partners. Some may not have them in .svg format but I'll let you know once we hear back.

**Comment by sarah-arrrgh** [comment]
Thanks @SlimeyD . It'd be helpful this end if you only put in the logos that you want us to use, or let us know which files are the ones you want. There are heaps of Action Station logos, and the only one that looks ready to roll is very small, perhaps too small. Is this something you can sort out for us?

**Comment by SlimeyD** [comment]
It's hard to know which ones are the best quality @sarah-arrrgh I've found a different ActionStation logo and am trying to differentiate by bringing one logo to the fore. If you don't think a logo is going to work, let me know. It seems like F&B and ActionStation don't have .svg files

**Comment by sarah-arrrgh** [comment]
@SlimeyD we're missing an icon for the "supporting biodiversity" value - can you please drop the svg file into the google drive icon folder and let me know when you've done so? <3

**Comment by SlimeyD** [comment]
@sarah-arrrgh it might be easier to make a record of outstanding elements. They're not all there and we'll likely need Elliot (or someone else) to design up some additional elements .You could add them to the dev board as I've got a few other assets that will need developing. In the meantime, can you account for additional icons/elements to be added to the survey?

**Comment by sarah-arrrgh** [comment]
@SlimeyD what do you mean "can you account for additional icons/elements to be added to the survey"?

**Comment by SlimeyD** [comment]
@sarah-arrrgh I've added a note to the content doc that hopefully helps explain. Beyond the 5 or 6 options currently under each heading ('I want to Invest in:' and "I don't want to invest in: ') there may be others ie. 'animal cruelty' and 'toxic and polluting industries'. Is it possible to leave the exact names and number of these open? I don't foresee more than 10 per heading.

**Comment by sarah-arrrgh** [comment]
@SlimeyD cool I've left you some comments on the doc :)

**Comment by ahdinosaur** [comment]
>  Fix styling in partner text to include links, italics, bold etc. (is there an easy way to do this @ahdinosaur ? The only way I can think of doing it is to break down each sentence into sub-sentences and add different styling to each part, which sounds like a pain in the ass...)

yeah, you could create helper functions like:

```js
function link ({ href, text }) {
  return h('a', {
    className: styles.link,
    href
  }, [
    text
  ]
}

function italics (text) {
  return h('span', {
    className: styles.italics
  }, [
    text
  ]
}

function bold (text) {
  return h('span', {
    className: styles.bold
  }, [
    text
  ]
}
```

and then

```js
h('div', {
  className: styles.partnerText // or whatever
}, [
  'hello',
  bold('there'),
  italics('beautiful'),
  link({ href: '#here', text: 'human' })
])
```

**Comment by sarah-arrrgh** [comment]
Thanks @ahdinosaur , I kinda get what you've done here, but not sure if you've taken into account that all the text on this website goes through that `intl` library and is in a translation json file. Where would those code snippets you posted live, in this scenario?

For example, one of the blurbs reads:
```
We’re working with the best and brightest in Socially Responsible Investment (SRI). Booster have two Socially Responsible funds certified by the Responsible Investment Association of Australasia - they also have the most comprehensive SRI Philosophy, which you can read here.
```

which lives in the translation json file like this:
```
"home.6b": "We’re working with the best and brightest in Socially Responsible Investment (SRI). Booster have two Socially Responsible funds certified by the Responsible Investment Association of Australasia - they also have the most comprehensive SRI Philosophy, which you can read here.",
```

and is passed into the component like this:
```
h(FormattedMessage, {
  id: 'home.6b'
})
```

**Comment by sarah-arrrgh** [comment]
Keen to get what I've done so far into `master` and carry over the rest of the undone todos to a new branch. I'm away for two weeks so then either I can pick it up again when I'm back or someone else can pick it up easily <3

**Comment by sarah-arrrgh** [comment]
Merging this in to `master` now, rebased what had been done since I've been away.

**Pull request merged**
